// src/lib/classificationValues.ts
// Single source of truth for data model classification values.
// Derived from actual LAG + SEG domain analysis data.

/** Business domain classification */
export const DATA_CATEGORY = [
  "AI Summary",
  "AR Reconciliation",
  "Appointment",
  "Balance",
  "Bank Statement",
  "Campaign & Appointment",
  "Collection",
  "Configuration",
  "Cost",
  "Data Hygiene",
  "Interco Transfer",
  "Invoice",
  "Invoice Items",
  "Mapping",
  "Master List",
  "Navigation",
  "Payment",
  "Payout",
  "Receipt",
  "Receipt Item Modifiers",
  "Receipt Loyalty",
  "Receipt Payments",
  "Receipt Promos",
  "Receipts",
  "Receipts & Targets",
  "Report",
  "Sales",
  "Staging",
  "Targets",
  "Test",
  "Transaction",
  "Unknown",
  "Usage",
  "Usage Items",
  "Utilisation",
] as const;

/** Granular classification within category */
export const DATA_SUB_CATEGORY = [
  "AR Reconciliation",
  "Aggregate",
  "Bank",
  "Brand",
  "Brand - Category",
  "Brand - Category - Item",
  "Brand - Channel",
  "Brand - Meal Slot",
  "Brand - Outlet",
  "Campaign",
  "Campaign Appointment ROI",
  "Cash",
  "Category",
  "Channel",
  "Customer",
  "DW-TA",
  "DW-UDT",
  "DW-US",
  "Data Ingestion",
  "Department",
  "Dispute Tracking",
  "Email Error",
  "Employee",
  "Fulfilment Type",
  "GL",
  "MS-AM",
  "MS-BM",
  "Meal Slot",
  "Operating Hours",
  "Outlet",
  "Outlet - Therapist",
  "Payment",
  "Platform",
  "Product",
  "Raw",
  "Resource",
  "Sales",
  "Sales & Bank",
  "Sales Transaction",
  "Solution",
  "Staff",
  "Status",
  "Stock",
  "UN",
  "Usage Intervals",
] as const;

/** Nature/behavior of the data */
export const DATA_TYPE = [
  "Aggregate",
  "Configuration / Settings",
  "Inventory",
  "Other",
  "Receipt",
  "Receipt Line Item",
  "Report",
  "Static",
  "Test",
  "Transactional",
  "Unknown",
] as const;

/** Operational status */
export const USAGE_STATUS = [
  "In Use",
  "Not Used",
  "Historically Used",
  "I Dunno",
] as const;

/** Review action */
export const ACTION = [
  "None",
  "To Review",
  "To Delete",
  "Approved",
] as const;

/** Where the data originates */
export const DATA_SOURCE = [
  "API",
  "Bank",
  "Custom Report",
  "ERP",
  "File Import",
  "Manual Upload",
  "Outlook",
  "POS",
  "Spreadsheet",
  "System Generated",
  "Unknown",
] as const;

/** Specific source system/vendor */
export const SOURCE_SYSTEM = [
  "2C2P",
  "Adyen",
  "Amex",
  "Aptsys",
  "Atlas",
  "Atlas Adyen",
  "DBS Bank",
  "Deliveroo",
  "Dine Connect",
  "Epoint",
  "Food Panda",
  "Grab",
  "KH App",
  "NetSuite",
  "Nets",
  "Novitee",
  "OCBC Bank",
  "Oddle",
  "Others",
  "Revel",
  "Shopback",
  "Stripe",
  "UOB Bank",
  "UOB CC",
  "Xilnex",
] as const;

/** Descriptive labels for tables (merged LAG + SEG) */
export const TAGS = [
  "2C2P",
  "AMEX",
  "AI",
  "Accounting",
  "Aggregation",
  "Analytical",
  "Analytics",
  "Appointment",
  "Appointment Management",
  "Attendance",
  "Availability",
  "Average",
  "Avg4W",
  "Bank",
  "Bank Statement",
  "Booking",
  "Boundary Splitting",
  "Brand",
  "Brand Analysis",
  "Brand Analytics",
  "Brand Channel",
  "Brand Performance",
  "Breakeven",
  "Campaign",
  "Cash Sales",
  "Cashback",
  "Channel",
  "Collection Report",
  "Commission",
  "Comparative Analysis",
  "Comparison",
  "Compliance",
  "Composition",
  "Configuration",
  "Cost",
  "Cost Analysis",
  "Cost Tracking",
  "Credit Card",
  "Customer",
  "Customer Balance",
  "Customer Engagement",
  "Customer Master",
  "Customer Metrics",
  "Customer Tracking",
  "Daily Metrics",
  "Data Quality",
  "Data Validation",
  "Delivery",
  "Detailed Item",
  "Detailed Line Item",
  "Diagnostic",
  "Dimension",
  "Dimensional Analysis",
  "Dine Connect",
  "Dining",
  "Discount",
  "Dispute",
  "ETL",
  "Email",
  "Employee",
  "Employee Performance",
  "Employee Scheduling",
  "Error Log",
  "Fee",
  "Feedback",
  "Fees",
  "Financial",
  "Financial Analysis",
  "Food Panda",
  "Fulfillment",
  "Fulfilment",
  "Fulfilment Type",
  "GL Entry",
  "Grab",
  "HR",
  "HR Analytics",
  "HR Transaction",
  "HRIS",
  "Hour Tracking",
  "Hour-level Analysis",
  "Integration",
  "Intercompany",
  "Inventory",
  "Invoice",
  "Item",
  "Item Breakdown",
  "Item Detail",
  "Item Details",
  "Item Modifier",
  "Lead",
  "Lead Tracking",
  "Line Item",
  "Loyalty",
  "MTD",
  "MTD Analysis",
  "Manual Upload",
  "Mapping",
  "Marketing",
  "Master Data",
  "Meal Slot",
  "Mealslot",
  "Membership",
  "Merchant",
  "Metrics",
  "MoM Metrics",
  "Modifier",
  "Monitoring",
  "Monthly Metrics",
  "Multi-Dimension",
  "Multi-Dimensional",
  "Multi-Period",
  "NETS",
  "Navigation",
  "Normalization",
  "Order",
  "Organizational",
  "Outlet",
  "Outlet Analysis",
  "Outlet Mapping",
  "Outlet Performance",
  "Overtime",
  "POS",
  "Payment",
  "Payout",
  "Performance",
  "Performance Analysis",
  "Performance Metrics",
  "Performance Tracking",
  "Period-over-Period",
  "Personnel",
  "Personnel Tracking",
  "Platform",
  "Pricing",
  "Product",
  "Profile",
  "Promo",
  "Promotion",
  "Promotion Analysis",
  "Promotional Analysis",
  "Query Management",
  "R-Squared",
  "Receipt",
  "Receipt Analysis",
  "Reconciliation",
  "Redemption",
  "Refund",
  "Report",
  "Reporting",
  "Resource Allocation",
  "Resource Scheduling",
  "Resource Utilization",
  "Retail",
  "Revenue",
  "Revenue Analysis",
  "Revenue Tracking",
  "Reviews",
  "Roster",
  "SKU",
  "Sales",
  "Sales Analysis",
  "Sales Analytics",
  "Sales Performance",
  "Sales Reconciliation",
  "Sales Report",
  "Scheduling",
  "Service Tracking",
  "Settlement",
  "Shift",
  "Shift Tracking",
  "Shopify",
  "Slope Analysis",
  "Staff",
  "Staff Hours",
  "Staff Management",
  "Staff Performance",
  "Staff Roster",
  "Staff Tracking",
  "Staff Utilization",
  "Staffing",
  "Staging",
  "Status",
  "Status Tracking",
  "Stock",
  "Stock Movement",
  "Stripe",
  "Supplier",
  "Target",
  "Target Tracking",
  "Tax",
  "Test Data",
  "Time Aggregate",
  "Time Boundary",
  "Time Series",
  "Time Tracking",
  "Timesheet",
  "Tracking",
  "Transaction",
  "Treatment",
  "Trend Analysis",
  "UOB",
  "UOM",
  "Unused",
  "Usage",
  "Usage Analytics",
  "Usage Tracking",
  "User Analysis",
  "Utilization",
  "Utilization Rate",
  "Validation",
  "Variance",
  "Variance Check",
  "Variation",
  "Verification",
  "Week",
  "Week-over-Week",
  "Weekly Metrics",
  "Weekly Report",
  "Work Hours",
  "Work Schedule",
  "Workforce",
  "Workforce Analytics",
  "Workforce Management",
  "Workflow",
  "YTD",
  "YTD Report",
  "for-ai",
] as const;

/** Dropdown values with empty string first for clearing in AG Grid editors */
export const DROPDOWN_VALUES = {
  dataCategory: ["", ...DATA_CATEGORY],
  dataSubCategory: ["", ...DATA_SUB_CATEGORY],
  dataType: ["", ...DATA_TYPE],
  usageStatus: ["", ...USAGE_STATUS],
  action: ["", ...ACTION],
  dataSource: ["", ...DATA_SOURCE],
  sourceSystem: ["", ...SOURCE_SYSTEM],
} as const;
