ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_type text NOT NULL DEFAULT 'work';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS intent text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES crm_companies(id);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_stage text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_value numeric;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_currency text DEFAULT 'SGD';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_solution text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_expected_close date;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_actual_close date;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_proposal_path text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_order_form_path text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_lost_reason text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_won_notes text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_stage_changed_at timestamptz;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_stale_snoozed_until timestamptz;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_contact_ids uuid[];
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_tags text[];
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deal_notes text;
CREATE INDEX IF NOT EXISTS idx_projects_type ON projects (project_type);
CREATE INDEX IF NOT EXISTS idx_projects_company ON projects (company_id) WHERE company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_projects_deal_stage ON projects (deal_stage) WHERE deal_stage IS NOT NULL;
ALTER TABLE workspace_sessions ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES projects(id);
ALTER TABLE workspace_artifacts ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES projects(id);
ALTER TABLE workspace_context ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES projects(id);
ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS project_id uuid REFERENCES projects(id);
